services:
  server:
    image: rodamianro/util:nextjs
    build:
      context: .
      target: ${ENVIRONMENT:-develop}
    networks:
      - net
    ports:
      - ${SERVER_PORT:-3000}:3000
    volumes:
      - ./nextjs-dashboard:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.pnpm-store
      - /home/node/app/.next
    tty: true
networks:
  net:
    driver: bridge
